### ISSUE TITLE
Loan Repayment Calculation

### ISSUE THREAD

**Issue by davidubanyi** [phosmobile-technologies/credit-business-management-app-api#73]
I have written the following function in javascript which calculates how much the loan owner is to pay per month for their loan, when the loan amount, interest rate and duration of the loan is inputted. However, this formula is to be used on the backend to determine how much the user is supposed to pay per month.

```
const getRepaymentAmount = (p,ir,d) =>{
  //p is the principal
  //ir is the interest rate
  //d is the loan duration in months
let base_payment = p/d;
let reducing_balance = p+base_payment;
let monthly_rate = 0;
let rate = ir/100
let i
for(i = 1; i <= d; i++ ){
reducing_balance -= base_payment;
monthly_rate += (reducing_balance * rate)
}
return (p + monthly_rate)/d
};
```

**Comment by enwemasor1995** [comment]
from loan model; Loan repayment frequency cant either be weekly on monthly
does this formula calculate for both or just for monthly

also, will the amount the user is supposed to pay,  persist in the database or just returned after t is created

**Comment by davidubanyi** [comment]
@enwemasor1995 this is for monthly, loans are repayed monthly the other frequencies are currently not practical, thanks for the question.

**Comment by enwemasor1995** [comment]
also, will the amount the user is supposed to pay, persist in the database or just returned after t is created
